name: Build-Deploy-Dev
on:
  push:
    branches: [develop]

env: 
  APP_NAME: bitorbit-synapse
  REPO: ${{ secrets.GAR_DEV }}/${{ secrets.GCP_DEV_PROJECT }}/docker
  IMAGE_TAG: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  ENVIRONMENT: dev

jobs:
  docker-build:
    name: Build and push
    runs-on: dev
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
      - name: Build, tag, and push image 
        env:
          DOCKER_BUILDKIT: 1
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_DEV }} -q
          docker build -t $REPO/$APP_NAME:$IMAGE_TAG . -f docker/Dockerfile
          docker tag $REPO/$APP_NAME:$IMAGE_TAG $REPO/$APP_NAME:${BRANCH_NAME}
          docker push $REPO/$APP_NAME:$IMAGE_TAG
          docker push $REPO/$APP_NAME:${BRANCH_NAME}
  deploy:
    name: Deploy via Helmfile
    runs-on: dev
    needs: docker-build
    steps:
      - name: Check out bitorbit-prod-infra
        uses: actions/checkout@v3
        with:
          repository: BitorbitLabs/bitorbit-prod-infra
          ref: master
          ssh-key: ${{ secrets.SSH_KEY_PROD_INFRA }}
      - name: Deploy via helmfile
        id: deploy
        run: >
          cd helmfile &&
          helmfile -e ${ENVIRONMENT} -l name=${APP_NAME}
          apply --skip-deps --suppress-diff
          --set image.tag=${IMAGE_TAG}
          --set image.repository=${REPO}/${APP_NAME}